### ISSUE TITLE
Wont import racks with same name in different rows/locations

### ISSUE THREAD

**Issue by dionrowney** [ITJamie/racktables2netbox#6]
We have Rack-1 in Row-1 and Row-2 and the same in different datacenters.

It seems to puke on Rack names that are already imported with the same name.

2022-09-13 10:28:35,601 - rt2nb - DEBUG - {'name': 'RACK-2', 'site': 428, 'comments': 'ROW 1', 'custom_fields': {'rt_id': '1382'}, 'tags': [], 'u_height': 40, 'location': 471}
2022-09-13 10:28:35,602 - rt2nb - INFO - checking for existing rack in netbox: https://hostname.usask.ca/api/dcim/racks/?name=RACK-2
2022-09-13 10:28:35,602 - rt2nb - DEBUG - HTTP Request: GET - https://hostname.usask.ca/api/dcim/racks/?name=RACK-2
2022-09-13 10:28:35,795 - rt2nb - DEBUG - HTTP Response: 200 - OK
Traceback (most recent call last):
  File ".\racktables2netbox.py", line 3814, in <module>
    racktables.get_infrastructure()
  File ".\racktables2netbox.py", line 2127, in get_infrastructure
    netbox.post_rack(netbox_rack)
  File ".\racktables2netbox.py", line 257, in post_rack
    if exists[0]:
TypeError: 'bool' object is not subscriptable

Is the a work around or do i have to change source Rack names in my 50 rooms to be distinct?

**Comment by ITJamie** [comment]
i can try and fix this in future, but for now you would be best to just temporarily re-name racks in your RT instance to get your migration done, there is a good chance you will end up renaming them in netbox post migration anyways once you figure out how you want to show data in netbox

**Comment by dionrowney** [comment]
I was able to take the locatiojn, row and rack names and combine them in your code for testing.  I may also add a random number to the end of the name in rack tables like you suggested (I have 100+ racks) with duplicate names (RACK-1 in location X) etc
